import { NextResponse } from "next/server"
import { writeFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import { randomBytes } from "node:crypto"
import { auditLog } from "@/lib/audit-log"

// In Docker: write to /app/data/.env (persistent volume, sourced by entrypoint)
// In dev: write to .env.local (Next.js reads it on startup)
const ENV_PATH = existsSync("/.dockerenv")
  ? "/app/data/.env"
  : `${process.cwd()}/.env.local`

// Only allow setup when no auth providers are currently configured.
// Once a provider is active, this endpoint is locked.
function isSetupAllowed(): boolean {
  const hasGoogle =
    !!process.env.GOOGLE_CLIENT_ID && !!process.env.GOOGLE_CLIENT_SECRET
  const hasResend = !!process.env.RESEND_API_KEY
  return !hasGoogle && !hasResend
}

export async function GET() {
  return NextResponse.json({ setupAllowed: isSetupAllowed() })
}

export async function POST(request: Request) {
  if (!isSetupAllowed()) {
    auditLog({
      event: "setup.attempt",
      outcome: "denied",
      actor: "anon",
      detail: { reason: "locked" },
    })
    return NextResponse.json(
      { error: "Setup is locked. Auth providers are already configured." },
      { status: 403 }
    )
  }

  const body = await request.json()
  const { googleClientId, googleClientSecret, resendApiKey, emailFrom } =
    body as {
      googleClientId?: string
      googleClientSecret?: string
      resendApiKey?: string
      emailFrom?: string
    }

  const hasGoogle = googleClientId && googleClientSecret
  const hasResend = resendApiKey
  if (!hasGoogle && !hasResend) {
    return NextResponse.json(
      { error: "Provide credentials for at least one auth provider." },
      { status: 400 }
    )
  }

  // Build env file — uses export syntax so the Docker entrypoint can source it
  const authSecret = randomBytes(32).toString("base64")
  const lines: string[] = [
    "# Auto-generated by setup wizard",
    `export AUTH_SECRET="${authSecret}"`,
    `export AUTH_URL="${process.env.AUTH_URL ?? "http://localhost:11000"}"`,
    `export DATABASE_URL="${process.env.DATABASE_URL ?? "file:/app/data/app.db"}"`,
  ]

  if (hasGoogle) {
    lines.push(`export GOOGLE_CLIENT_ID="${googleClientId}"`)
    lines.push(`export GOOGLE_CLIENT_SECRET="${googleClientSecret}"`)
  }

  if (hasResend) {
    lines.push(`export RESEND_API_KEY="${resendApiKey}"`)
    lines.push(`export EMAIL_FROM="${emailFrom ?? "onboarding@resend.dev"}"`)
  }

  await writeFile(ENV_PATH, lines.join("\n") + "\n", "utf-8")

  auditLog({
    event: "setup.complete",
    outcome: "success",
    actor: "anon",
    detail: { provider: hasGoogle ? "google" : "resend" },
  })

  const isDocker = existsSync("/.dockerenv")

  if (isDocker) {
    // Respond first, then exit. Docker's restart policy brings it back.
    // The entrypoint script will source /app/data/.env before starting node.
    setTimeout(() => process.exit(0), 500)
    return NextResponse.json({
      success: true,
      message: "Configuration saved. Container is restarting...",
      restart: true,
    })
  }

  return NextResponse.json({
    success: true,
    message:
      "Configuration saved. Restart your dev server to apply the changes.",
    restart: false,
  })
}
